### ISSUE TITLE
Excel friendly output csvs

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsProduction#139]
One of the issues Tomasz brought up in his email was:

> 1. Any improvements or suggestions on the output (attachments in the email) - in many cases in "measuredItemCPC" are missing "0",  for example: 1371 instead of 01371 (Almonds, in shell)

Excel is just awful at opening csvs. I've attached two. One is Excel compatible, and the other isn't. It's a pretty awful hack, but it's something to consider. I understand if you file this as `wontfix`.

[badcsv.txt](https://github.com/SWS-Methodology/faoswsProduction/files/286338/badcsv.txt)
[goodcsv.txt](https://github.com/SWS-Methodology/faoswsProduction/files/286339/goodcsv.txt)

**Comment by mkao006** [comment]
Had a small discusision with Tomasz and also searched online. This is an excel problem and I have not find an immediate quick solution. Will not fix it for now.

**Comment by mkao006** [comment]
Tomasz found a way to correctly import the file into excel.

> Great, thank you.
> 
> Then, the solution for "0" is to import txt file into Excel file choosing the correct format (Text) for item codes.
> 
> Tomasz
