### ISSUE TITLE
Exclude outliers from the imputation process

### ISSUE THREAD

**Issue by carola-f** [SWS-Methodology/faoswsProduction#198]
The production dataset contains many official outliers that affect the imputed values. These values will not be deleted from the dataset, but should not enter in the imputation model .

**Comment by mkao006** [comment]
This is current not possible, as when models are fitted they use all the values in the data. From a valid statistical point of view, they are two approach to address this.
1. Investigate and correct the outlier.
2. Adjust the model to be more robust to outliers. 

My take on this is that this is not an issue to be address by the methodological team. The distinction is clear, this is a data collection problem.

**Comment by carola-f** [comment]
This issue can be closed. 
The request stemmed from the need to publish imputations without undergoing the necessary extensive checks on the basic dataset. The request was dropped because it was not feasible.
