### ISSUE TITLE
Some commodities not present in the table

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsProduction#199]
The following commodity codes are present in `fbs_production_comm_codes`, but not in `agriculture:aproduction`
- 01241.02 - [This document](www.fao.org/fileadmin/templates/ess/classifications/Corr_3DEC2015_C.xlsx) says: Changed CPC expanded code for "Other beans, green" (FCL 0414) from 01241.02 to 01241.90
- 01929.91 - I think this was Agave fibres. The code for that on `agriculture:aproduction` is 01929.06

**Comment by francescafenix** [comment]
I added the correct codes into the reference-table.

**Comment by sebastian-c** [comment]
I ended up fixing this problem in the feed module as well. I recommend that all modules check for these codes.
