### ISSUE TITLE
R files need to be documented in README

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsProduction#30]
It's not clear what the difference is between imputeModel.R and productionImputationModel.R

**Comment by mkao006** [comment]
I think they are the same module, however the `productionImputationModel` module is no longer used I believe.

**Comment by mkao006** [comment]
The R files here refer to **modules/plug-ins**, correct?

**Comment by sebastian-c** [comment]
Yes, in this particular case, they are.

**Comment by mkao006** [comment]
No longer required.
