### ISSUE TITLE
Primary commodity codes

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsProduction#6]
The getMainKey function currently looks up a .csv file to determine which primary codes need to be imputed.  This is definitely bad practice, and should be fixed as soon as we have a reliable list of primary codes on the SWS.

**Comment by sebastian-c** [comment]
This was brought up in issue SWS-1258, which has been superseded by SWS-1296 which will add a table for each module.

**Comment by mkao006** [comment]
The function has been replaced by `getCompleteImputationKey` and reads from the **fbs_production_comm_codes** Datatable on the system.

**Comment by sebastian-c** [comment]
Could you please confirm that none of the files mentioned in [SWS-1258](https://jira.fao.org/ciok/browse/SWS-1258) are needed so that the issue can be closed?

**Comment by mkao006** [comment]
No, this is only associated with the `allImputationCodes.csv`.

The issue with `slaughtered_synchronized.csv` is superseded with Github issue #128 which has a different Jira issue.

I can't confirm for the stock file, looking at the name it is probably obsolete but please confirm with @vidigal88 .

**Comment by sebastian-c** [comment]
I've closed [SWS-1258](https://jira.fao.org/ciok/browse/SWS-1258) as none of the files are required. SWS-1296 is already closed.
