### ISSUE TITLE
Number of official observations required

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsProduction#9]
The current module uses estimated figures when there are fewer than 5 official/semi-official observations in the historical time series; otherwise it uses only official/semi-official data.  The choice of 5 was somewhat arbitrary, and it would be interesting to select that value from the data.

We could study the MSE difference (or, possibly the mean percent error difference, given the huge variability in production from country to country) between the two estimation approaches for differing numbers of official figures.  We could then choose the threshold when this MSE difference becomes small, as that would represent the point at which models using only a few official observations become unstable.

**Comment by mkao006** [comment]
This problem arose from historical specification of remove values and not being imprecise. The "E"stimate has flag "e" and "f", where the method flag "e" is always removed while "f" always retained.

A new flag is provided, the goal of imputation should be based on the set of data considered valid and reliable attempting to impute as much as possible.
